services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: node-app
    runtime: node
    repo: https://github.com/louisdrf/esgi4AL-render.git
    buildCommand: " npm install"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL 
        fromDatabase:
          name: esgi4AL-render-postgresql
          property: connectionString
