services:
  - type: web
    runtime: node
    name: my-app
    buildCommand: npm install
    startCommand: npm run start
    region: frankfurt
    plan: free
    envVars:
      - key: POSTGRES_INTERNAL_URL
        fromDatabase:
          name: my-app-db
          property: connectionString
    
databases:
  - name: my-app-db
    plan: free
    region: frankfurt
  